language: node_js
node_js:
  - 6
deploy:
  provider: heroku
  api_key:
    secure: DxjPkbV9q9IgxMjveleb0sr/MGOoPwfYmnaTBGU0qaeg5gQ4rVJnNn9LOnkbcJoOsogxVIiYMtz541HEQDyhfSgA9uOT+La3VV2hXkO0VnozdXQ6ASIyNhZ7oz/79ScKZUqUwbddzjksUg+dgmo7V//qBjeoIOGJZnHgbI+ZE2LpYzBioQSTifKjbTZBXVTYYji3+x7FbkOTir9/gagF18azTV+RrSQH8FrxjY17gmHxNrZX0KwNOQPljeS6YHVmIOwWetxnhoLZpnR84OewreKgVuBhtq7aEF3vH4x0oXnflnB5q4iWB9OVjNi/wWACupt9T7r1I6J+iU38Pc806Aa7wDmGMoI2zJhCb9TpR1536+xxKf32g/huCpZawXl5QFlr+2abMZq1wmqPlmJcVKjYY0bHWSVUzN7cvYz2INp0D6gtE7flDA8OmaR8n9zD1A3CD/ggnTo9uDKLNW8u+3STtTubg8GSksSSGIsQeoANQ4trrrpeh7yLfDJXAssnZYnO+w/Gsv8gQagtEi0JCuPKcPgU7fdRtqo7ZFLsEl85K7pMkqEZELLgjVcjjQuNxN3uju5KsbvOdo856LrfWPHqFqIqx0kukP0jVS9uieZ9OU1Elx4cNaKutBnZkL0yhZE+iK1a79k8OSzo+prq3jNeVvkv7jY8ZsOS8CMbhro=
    app: brain404frontend
    on:
      branch: dev
