language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: g9VCORaOyHrWyL8qzN/0EIu5BHEb0qnZQ5MPcl18Kb2UY9VjtbsDlPhF/7zV8inuIuyCWxRkAEP9K/e8DjE+dI+RQQvLbKccePTHVGnov+dNjqXwAS/QmEolQmgLFc+V8tHa+ibzNPJrZE3Bawo814kMNk4BmkuxZ17cYMDLylyDqD2iMn0OYlafAzbS/Q+qR8GwVBoERVI+nbubvLc7tLnG+490umXu0rvE3CjndZfPaGLZ6e85SVhpSYYpHpzfMf63KvFLXhRK4nsaqProaBhe/anwoLJpTZKj7c5Puaarax0JZSKNAjULsPilfV5I3oDl56W7US7TR+Cq+u176OuS3dwbrD/WcgLU+APBMROfVFktjHfNQNl9L8u5cmWo1jqUy6o4d7Q+2vprtrcPpcKXxparEmure94iVEoNCmeX60TOcFVlFiBgwQO7N8f3T0mI9GwSJlhzX6/PYo7zp2FGnM/aclvlgOieugThzwxkM/aVx6D/n/PHR+I0z7A+ht6/5EWU19wgv70tEX7APaarnLzjE1bRCyNVcYqisHXZswt2gb+I8Y0jpeNBpP+iGX1kv7+75xdtlkdlu5cT6+prP5YQTNdcdaKxWScqBvja0uys+u+q+fRKvrlI6QuqLoR5IRCpAzA5GqtOS4H1xuUZnmiil14mEr+/7sY5fcw=
  app: brain404frontend
  on: dev
